name = "atlas-gtfs-rt-archiver"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "atlas-live"

[triggers]
crons = ["* * * * *"]
