import React, { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Shield,
    RefreshCcw,
    Upload,
    Settings,
    CheckCircle2,
    AlertTriangle,
    Download,
    HelpCircle
} from 'lucide-react';
import { AnalysisResult, GtfsData } from '../../types/gtfs';
import { ModuleHeader } from '../../components/ModuleHeader';
import { EmptyStateHero } from '../../components/EmptyStateHero';
import { ModuleLanding } from '../../components/ModuleLanding';
import { useGtfsWorker } from '../../hooks/useGtfsWorker';
import { useAuthStore } from '../../hooks/useAuthStore';
import { useTransitStore } from '../../types/store';
import { useNotificationStore } from '../../hooks/useNotification';
import './Verifier.css';

export default function VerifierView() {
    const { isAuthenticated } = useAuthStore();
    const {
        gtfsData,
        analysisResults,
        setResults,
        loadPersistedData,
        clearData
    } = useTransitStore();

    const { addToast } = useNotificationStore();
    const [queue, setQueue] = useState<AnalysisResult[]>([]);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [urlTemplate, setUrlTemplate] = useState('https://agency-website.com/schedules/{{route}}');
    const [markedHeadway, setMarkedHeadway] = useState<string>('');
    const [streak, setStreak] = useState(0);
    const [stats, setStats] = useState({ correct: 0, wrong: 0, total: 0 });

    const fileInputRef = useRef<HTMLInputElement | null>(null);
    const { loading, status, runAnalysis } = useGtfsWorker();

    // Persist data on load
    useEffect(() => {
        if (!gtfsData) {
            loadPersistedData();
        }
    }, [loadPersistedData, gtfsData]);

    useEffect(() => {
        if (analysisResults.length > 0 && queue.length === 0) {
            setQueue([...analysisResults].sort(() => Math.random() - 0.5));
        }
    }, [analysisResults, queue.length]);

    const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        runAnalysis(file, async (data) => {
            await setResults(data);
            addToast('GTFS loaded for verification', 'success');
        });
    };

    const handleDecision = useCallback(async (type: 'correct' | 'wrong' | 'unsure') => {
        if (currentIndex >= queue.length) return;

        const current = queue[currentIndex];
        const updatedClaim = {
            ...current,
            verifiedHeadway: markedHeadway ? parseInt(markedHeadway) : undefined,
            verificationStatus: type
        };

        const newQueue = [...queue];
        newQueue[currentIndex] = (updatedClaim as any);
        setQueue(newQueue);

        // Update store which handles persistence
        if (gtfsData) {
            await setResults({ gtfsData, analysisResults: newQueue, spacingResults: [] });
        }

        setStats(prev => ({
            ...prev,
            [type]: (prev as any)[type] + 1,
            total: prev.total + 1
        }));

        if (type === 'correct') setStreak(s => s + 1);
        else setStreak(0);

        setMarkedHeadway('');
        setCurrentIndex(prev => prev + 1);
    }, [currentIndex, queue, markedHeadway]);

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'q' || e.key === 'Q') handleDecision('correct');
            if (e.key === 'w' || e.key === 'W') handleDecision('wrong');
            if (e.key === 'e' || e.key === 'E') handleDecision('unsure');
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [handleDecision]);

    const currentClaim = queue[currentIndex];

    if (loading) {
        return (
            <div className="atlas-page flex items-center justify-center">
                <div className="flex flex-col items-center space-y-4">
                    <div className="w-10 h-10 border-2 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin" />
                    <div className="text-center">
                        <p className="atlas-label mb-1">Audit Engine</p>                        <p className="text-xs font-mono text-indigo-400 font-bold">{status}</p>
                    </div>
                </div>
            </div>
        );
    }

    if (!isAuthenticated) {
        return (
            <ModuleLanding
                title="Audit"
                description="Technical GTFS validation and spec compliance auditing for professional transit networks."
                icon={Shield}
                features={[
                    {
                        title: "AI-Generated Claims",
                        description: "Audit frequencies generated by our proprietary AI transit engine.",
                        icon: <Shield className="w-5 h-5 text-indigo-500" />
                    },
                    {
                        title: "Schedule Auditing",
                        description: "Compare claims against real-world agency schedules in a side-by-side view.",
                        icon: <CheckCircle2 className="w-5 h-5 text-indigo-500" />
                    },
                    {
                        title: "Manual Consensus",
                        description: "Provide human-in-the-loop validation to ensure 100% data accuracy.",
                        icon: <Settings className="w-5 h-5 text-indigo-500" />
                    },
                    {
                        title: "Export Results",
                        description: "Generate verified frequency files ready for production network modeling.",
                        icon: <Download className="w-5 h-5 text-indigo-500" />
                    }
                ]}
            />
        );
    }

    if (!gtfsData) {
        return (
            <div className="module-container">
                <EmptyStateHero
                    icon={Shield}
                    title="Audit"
                    description="Audit AI-generated frequency claims against real-world agency schedules."
                    primaryAction={{
                        label: "Start Validation Task",
                        icon: Upload,
                        onClick: () => fileInputRef.current?.click()
                    }}
                />
                <input
                    type="file"
                    accept=".zip"
                    className="hidden"
                    ref={fileInputRef}
                    onChange={handleFileUpload}
                />
            </div>
        );
    }

    if (currentIndex >= queue.length) {
        return (
            <div className="verifier-container items-center justify-center">
                <div className="glass-panel p-12 text-center space-y-6 max-w-md">
                    <CheckCircle2 className="w-16 h-16 text-emerald-400 mx-auto" />
                    <h2 className="atlas-h2">Audit Complete</h2>
                    <p className="text-[var(--text-muted)]">You've verified all routes in this feed.</p>
                    <div className="flex flex-col gap-3 w-full">
                        <button
                            onClick={() => {
                                const blob = new Blob([JSON.stringify(queue, null, 2)], { type: 'application/json' });
                                const url = URL.createObjectURL(blob);
                                const a = document.createElement('a');
                                a.href = url;
                                a.download = 'verified-frequencies.json';
                                a.click();
                            }}
                            className="btn-primary w-full justify-center py-4"
                        >
                            <Download className="w-4 h-4" /> Export Verified Data
                        </button>
                        <button
                            onClick={async () => {
                                await clearData();
                                addToast('Data cleared', 'info');
                            }}
                            className="btn-secondary w-full justify-center py-4"
                        >
                            <RefreshCcw className="w-4 h-4" /> Reset and Restart
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="module-container">
            <ModuleHeader
                title="Audit"
                badge={{ label: "Phase 2 Verification", color: "text-amber-600 dark:text-amber-400 bg-amber-500/10 border-amber-500/20" }}
                actions={[
                    {
                        label: "Streak: " + streak,
                        variant: 'secondary',
                        onClick: () => { }
                    },
                    {
                        label: "Set Schedule URL",
                        icon: Settings,
                        variant: 'secondary',
                        onClick: () => {
                            const template = prompt('Enter URL template (use {{route}} for route number):', urlTemplate);
                            if (template) setUrlTemplate(template);
                        }
                    },
                    {
                        label: "Export",
                        icon: Download,
                        variant: 'primary',
                        onClick: () => {
                            const blob = new Blob([JSON.stringify(queue, null, 2)], { type: 'application/json' });
                            const url = URL.createObjectURL(blob);
                            const a = document.createElement('a');
                            a.href = url;
                            a.download = `verified-progress-${currentIndex}.json`;
                            a.click();
                        }
                    }
                ]}
            />

            <div className="verifier-arena">
                <div className="verifier-pane glass-panel">
                    <div className="pane-header">
                        <h2 className="pane-title">AI engine output</h2>
                        <span className="atlas-label bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 px-2 py-0.5 rounded border border-emerald-500/20">Live feed</span>
                    </div>
                    <div className="pane-content">
                        <AnimatePresence mode="wait">
                            {currentClaim && (
                                <motion.div
                                    key={currentClaim.route}
                                    initial={{ opacity: 0, x: -20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: 20 }}
                                    className="claim-card"
                                >
                                    <div className="atlas-label text-indigo-500 mb-2">Route Analysis</div>
                                    <div className="claim-route">{currentClaim.route}</div>
                                    <div className="claim-tier">{currentClaim.tier === 'span' ? 'Span' : `${currentClaim.tier}m`}</div>

                                    <div className="claim-details">
                                        <div className="claim-detail-item">
                                            <div className="detail-label">Service Day</div>
                                            <div className="detail-value text-indigo-500">{currentClaim.day}</div>
                                        </div>
                                        <div className="claim-detail-item">
                                            <div className="detail-label">Trips</div>
                                            <div className="detail-value text-emerald-500">{currentClaim.tripCount}</div>
                                        </div>
                                    </div>

                                    <div className="mt-8 text-sm text-[var(--text-muted)] leading-relaxed">
                                        Analyze the provided agency schedule and confirm if the proposed service tier accurately reflects the route's operational frequency.
                                    </div>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </div>

                <div className="verifier-pane flex-[2]">
                    <div className="pane-header">
                        <h2 className="pane-title">Reference material</h2>
                        <div className="flex items-center gap-4">
                            <span className="atlas-label font-mono text-[9px] opacity-60 truncate max-w-[300px]">{urlTemplate}</span>
                        </div>
                    </div>
                    <div className="pane-content">
                        <iframe
                            src={urlTemplate.replace('{{route}}', currentClaim?.route || '')}
                            className="evidence-frame"
                            title="Evidence Panel"
                        />
                    </div>
                </div>

                <div className="verifier-pane decision-pane">
                    <div className="pane-header">
                        <h2 className="pane-title">Consensus</h2>
                    </div>
                    <div className="decision-buttons">
                        <div className="mb-6">
                            <label className="atlas-label mb-2 block">Mark Frequency (mins)</label>
                            <input
                                type="number"
                                value={markedHeadway}
                                onChange={(e) => setMarkedHeadway(e.target.value)}
                                placeholder="Enter observed headway..."
                                className="w-full bg-[var(--item-bg)] border border-[var(--border)] rounded-xl px-4 py-3 font-mono font-bold text-lg focus:outline-none focus:border-indigo-500"
                            />
                        </div>

                        <button
                            className="decision-btn btn-correct"
                            onClick={() => handleDecision('correct')}
                        >
                            <div className="w-8 h-8 rounded-full bg-emerald-500/10 flex items-center justify-center">
                                <CheckCircle2 className="w-5 h-5" />
                            </div>
                            <div className="flex-1 text-left">
                                <div>Correct</div>
                                <div className="atlas-label opacity-60">Verified</div>
                            </div>
                            <span className="key-hint">Q</span>
                        </button>

                        <button
                            className="decision-btn btn-wrong"
                            onClick={() => handleDecision('wrong')}
                        >
                            <div className="w-8 h-8 rounded-full bg-red-500/10 flex items-center justify-center">
                                <AlertTriangle className="w-5 h-5" />
                            </div>
                            <div className="flex-1 text-left">
                                <div>Wrong</div>
                                <div className="atlas-label opacity-60">Flag anomaly</div>
                            </div>
                            <span className="key-hint">W</span>
                        </button>

                        <button
                            className="decision-btn btn-unsure"
                            onClick={() => handleDecision('unsure')}
                        >
                            <div className="w-8 h-8 rounded-full bg-amber-500/10 flex items-center justify-center">
                                <HelpCircle className="w-5 h-5" />
                            </div>
                            <div className="flex-1 text-left">
                                <div>Unsure</div>
                                <div className="atlas-label opacity-60">Request review</div>
                            </div>
                            <span className="key-hint">E</span>
                        </button>

                        <div className="mt-auto p-4 bg-[var(--item-bg)] border border-[var(--border)] rounded-xl">
                            <div className="atlas-label mb-3">Operator Guidelines</div>
                            <ul className="space-y-2">
                                <li className="text-[11px] text-[var(--text-muted)] flex items-start gap-2">
                                    <div className="w-1 h-1 rounded-full bg-indigo-500 mt-1.5 flex-shrink-0" />
                                    Frequency must match "Freq" if headway is &lt; 15 mins.
                                </li>
                                <li className="text-[11px] text-[var(--text-muted)] flex items-start gap-2">
                                    <div className="w-1 h-1 rounded-full bg-indigo-500 mt-1.5 flex-shrink-0" />
                                    Check span of service for "Span" tier.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
